### PR TITLE
LoKi functor lesson

### PR DESCRIPTION
**Pull request by apuignav**
Describe LoKi functors, types, etc, and how to use them. Trying to address #14 and #11.

### CODE REVIEW

**Comment by ibab** [comment]
So far, the lesson describes what LoKi functors are in terms of their inputs/outputs and which categories of functors there are.
I think it would be nice to start with some motivation on why they're useful.
Like

> LoKi functors are designed to flexibly compute and compare properties of the current decay.
> For example, the functor 'PT' gives you the tranverse momentum of a particle.
> Internally, functors are implemented as C++ classes.
> ...

But I don't know that much about LoKi functors. What do you think?

**Comment by apuignav** [comment]
Nice idea, it's really missing an introduction. Let's see how I implement
it.

**Comment by betatim** [comment]
Some motivation would be good as well as some examples of doing stuff with them. From the easy ones like `PT` to trying to get info about a vertex associated to your particle where you have to use `BPV` and weird stuff like that.

What is the most ambitious/complicated use of LoKi functors you have ever seen? We should take that as a final puzzle and explain it at the very end.

**Comment by apuignav** [comment]
Yes yes, this was just the starting point. Now I'll try to explain how to
use them using the `explore-dst` session.

On Tue, May 26, 2015 at 1:35 PM, Tim Head notifications@github.com wrote:

> Some motivation would be good as well as some examples of doing stuff with
> them. From the easy ones like PT to trying to get info about a vertex
> associated to your particle where you have to use BPV and weird stuff
> like that.
> 
> What is the most ambitious/complicated use of LoKi functors you have ever
> seen? We should take that as a final puzzle and explain it at the very end.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lhcb/first-analysis-steps/pull/48#issuecomment-105494841
> .

## 

Dr. Albert Puig Navarro
Laboratoire de Physique des Hautes Energies
Ecole Polytechnique Fédérale de Lausanne (EPFL)
BSP 614.4 (Cubotron UNIL) CH-1015 Lausanne
EPFL Phone: 021 6939808
CERN Phone: 72518

**Comment by apuignav** [comment]
Right now I have the basic LoKi functors. The problem is that showing them in an interactive GaudiPython (the easiest) gives some nasty errors + we cannot use the BPV functors. Ideas?

**Comment by apuignav** [comment]
So, should we go deeper? Which are your favorite functors to include?

**Comment by ibab** [comment]
This is awesome!
Can you add a link to the example code and an invitation to try it out at the very end?

**Comment by apuignav** [comment]
Should be OK now.

**Comment by apuignav** [comment]
I think `SUMTREE` and `ABSID` were important. Added and ready to merge.

**Comment by ibab** [comment]
Looks good!
I'm merging this.

**Pull request merged**
