### PR TITLE
Add a few fixes to lesson 07-minimal-dv

### PR DESCRIPTION
**Pull request by ibab**
These are the fixes referenced in #7.

### CODE REVIEW

**Comment by betatim** [comment]
paging soon-to-be doctor @alexpearce, the stream name difference is because MC <-> Data?

**Comment by ibab** [comment]
Right, there's no /Event/CharmCompleteEvent in the MC DST

**Comment by betatim** [comment]
LGTM, so we merge it then?

**Comment by ibab** [comment]
Maybe Alex has a comment. We can always work on something else in the meantime :)

**Comment by alexpearce** [comment]
Sorry for the delay. All looks good, thanks very much for the spotting the mistakes.

**Pull request merged**
