### PR TITLE
Pep8 ify

### PR DESCRIPTION
**Pull request by alexpearce**
Related to #70, fixes (nearly) all of the warnings that [`pep8`](https://pypi.python.org/pypi/pep8) emits on everything in `code/`, and mirrors those changes in the `.md` lessons. I've tried to make the coding style consistent.

There's a whole bunch o' warnings from `data/` and `tools/` that I haven't tried to deal with.  The remaining stuff in `code/` is

```
code/dst-explore.py:108:80: E501 line too long (102 > 79 characters)
code/dst-explore.py:110:80: E501 line too long (86 > 79 characters)
code/11-davinci-grid/first-job.py:4:80: E501 line too long (187 > 79 characters)
code/12-split-jobs/first-job.py:4:80: E501 line too long (187 > 79 characters)
```

I'm not sure how to break these lines up. We could append [`# noqa`](https://github.com/jcrocholl/pep8/pull/136) to the lines, but then those comments would need to be explained, else they'll be copied.

### CODE REVIEW

**Comment by betatim** [comment]
We could break up the long strings and rely on string continuation (or what ever the jargon is for "blah" "blah" on two lines being combined into "blahblah"). I think that is easier to explain than `# noqa`

**Comment by alexpearce** [comment]
That would mean this:

``` python
j.inputdata = j.application.readInputData('data/MC_2012_27163003_Beam4000GeV2012MagDownNu2.5Pythia8_Sim08e_Digi13_Trig0x409f0045_Reco14a_Stripping20NoPrescalingFlagged_ALLSTREAMS.DST.py')
```

in to something like this:

``` python
j.inputdata = j.application.readInputData((
    'data/'
    'MC_2012_27163003_Beam4000GeV2012MagDownNu2.5'
    'Pythia8_Sim08e_Digi13'
    '_Trig0x409f0045_Reco14a_Stripping20NoPrescalingFlagged'
    '_ALLSTREAMS.DST.py'
))
```

split somewhat arbitrarily.

The decay descriptors are slightly harder to split, personally. How about from this:

``` python
# works
# decay_desc = '[[B0]cc -> (^D- => {^K- ^K+ ^pi-, ^K- ^pi+ ^pi-,^pi+ ^pi- ^pi-, ^K- ^K- ^pi+}) ^K-]cc'
# doesn't work
decay_desc = '[[B0]cc -> (^D- => {^K- ^K+ ^pi-, ^K- ^pi+ ^pi-,^pi+ ^pi- ^pi-}) ^K-]cc'
```

to this?

``` python
# works
decay_desc = (
    '[[B0]cc -> '
    '(^D- => {^K- ^K+ ^pi-, ^K- ^pi+ ^pi-,^pi+ ^pi- ^pi-, ^K- ^K- ^pi+})'
    '^K-]cc'
)
# doesn't work
decay_desc = (
    '[[B0]cc -> (^D- => {^K- ^K+ ^pi-, ^K- ^pi+ ^pi-,^pi+ ^pi- ^pi-}) ^K-]cc'
)
```

**Comment by betatim** [comment]
Both BK path and decay descriptor look fine.

Don't think there is an ideal solution. Maybe we add a comment to each to explain what is happening for those not deep into python parser grammar?

**Comment by alexpearce** [comment]
Maybe it's taught in one of the SWC lessons?

**Comment by alexpearce** [comment]
`pep8 code` now emits no warnings.

I would like to get this merged before the lessons, as having a consistent coding style (done to a standard) is important.

**Comment by seneubert** [comment]
Where are these DecayDescriptors coming from? They look suspiciously like old style ones, no? Also charges are wrong.

Shouldn't it be

``` python
decay_desc = (
    '[ B0 -> '
    '^(D- -> {^K- ^K+ ^pi-, ^K- ^pi+ ^pi-,^pi+ ^pi- ^pi-, ^K- ^K- ^pi+})'
    '^K+]CC'
)
```

Also, please note that this notation is looking super strange for anybody not very familiar with python. Please make a comment in the code if you use it.

Would like to merge because I think the pep8 stuff is good. But with these issues remaining we can't stop here. Ideas?

**Comment by alexpearce** [comment]
I just formatted the descriptors that were there. If they are wrong we should change them, I agree. I would have we could get rid of them completely though, seeing as they are unrelated to the D*+ chain we'll be testing with.

The notation is first [explicitly explained in the Building Decays](https://github.com/lhcb/first-analysis-steps/pull/79/files#diff-2f3939c27f5f02116dd8f2e6d8b384c8R82) lesson.

You're right not to merge if there are outstanding issues.

**Comment by betatim** [comment]
Let;s get rid of them. They are only in `dst-explorer.py` because I dumped a script I had there as a starting point. That part is never used in an y of the examples, we maybe can even get rid of `dst-explorer.py` all together?

If you add a commit removing the lines (I'd keep the file for the moment as I don't know off the top of my head if it is used or not) then we can merge this.

Sorry for not realising earlier that we were chasing a red herring, too busy trying to think how to solve the problem instead of big picture.

(Yes some of them are old style, at the time what I was doing was trying to understand how the decay finder tools work with old and new)

**Comment by alexpearce** [comment]
Agree to keep for now. I've removed the lines and tidied the decay descriptor finding stuff.

**Comment by betatim** [comment]
Thank you for making travis' brain even smarter! :slot_machine:

**Comment by alexpearce** [comment]
we just need #70 to add the check to the tests.

**Comment by betatim** [comment]
Think my comment about `pep8 .` in #70 is wrong, should be `pep8 code`

//Paging @kdungs

**Pull request merged**
