### PR TITLE
Fix dtt.Decay

### PR DESCRIPTION
**Pull request by mick-mulder**
Fixed mistake in dtt.Decay definition such that not only Dstar variables, but all variables for all particles, are written to ntuple.

### CODE REVIEW

**Comment by betatim** [comment]
I think it is like this on purpose as the corresponding lesson goes on to tell people that probably the best thing to do is use explicit branches. What do the others thing?

If we change it we should probably also change `code/12-add-tupletools/ntuple_options_loki.py`

**Comment by betatim** [comment]
I forgot: Welcome to contributing to the starterkit!

**Comment by mick-mulder** [comment]
Thank you! 

Indeed, this lesson advises people to use branches. However, the branches with daughter particles cannot be filled unless the corresponding daughter particles have been marked with a ^ in the dtt.Decay definition. After copying this file directly, I got the following error message (for all of the daughters, I have just included this one for brevity):

> TupleDstToD0pi_...SUCCESS  #ERRORS     = 1        Message = 'The decay descriptor 'TupleDstToD0pi_D0ToKpi.D0 : ( ( D_(2010)+  -> ^( ( D0  -> K-  pi+ ) ) pi+ ) || ( D_(2010)-  -> ^( ( D~0  -> K+  pi- ) ) pi- ) ) ' returned a match which is not also matched by your main decay descriptor. Ignoring it.'

As a result, the variables were not written to the ntuple. 

Including the marks in the decay description made the code run without these errors, and led to an ntuple with the variables associated with the daughter particles.

**Comment by betatim** [comment]
Ah ok, can you also change it in `code/12-add-tupletools/ntuple_options_loki.py` by pushing another commit to the same branch in your fork. Then we can merge it.

**Comment by mick-mulder** [comment]
I will change it right now, thanks for the heads-up!

**Comment by mick-mulder** [comment]
I just included the same fix for `code/12-add-tupletools/ntuple_options_loki.py`, could the branches now be merged?

**Comment by betatim** [comment]
Purfect :cat2:

Thank you for contributing: :beers:

**Pull request merged**
