### PR TITLE
[WIP] Redoing the EOS storage part

### LINKED ISSUE #8: EOS intro
5min introduction to what EOS is, why you want to use it (put job output there because your AFS is too small), `eosmount`,

### PR DESCRIPTION
**Pull request by betatim**
Fixes #8, still needs some lines about how to access your EOS files. Based on stuff from #21 that was abandoned.

### CODE REVIEW

**Comment by betatim** [comment]
[EOS docs](http://eos.cern.ch/index.php?option=com_content&view=article&id=87:using-eos-at-cern&catid=31:general&Itemid=41)

**Comment by ibab** [comment]
Maybe it would make sense to split the EOS command line/ROOT part into a separate lesson?

**Comment by betatim** [comment]
I am happy with it as it is now. Decided to keep it in one topic instead of splitting it up (left as improvement for the student after the starterkit ... or some other excuse like that).

@ibab take a look and then merge if there are no more outstanding issues.

**Comment by ibab** [comment]
Looks good!

**Pull request merged**
