### PR TITLE
Add lesson on using SVN

### PR DESCRIPTION
**Pull request by alexpearce**
Merge it quickly :wink:

### CODE REVIEW

**Comment by betatim** [comment]
Who owns the analysis note that everyone will be committing to?

**Comment by alexpearce** [comment]
I guess I could do it seeing as I'm not instructing atm?

**Comment by kdungs** [comment]
So is this good to merge or what?

**Comment by alexpearce** [comment]
One sec, just adding some info on LHCb docs.

**Comment by alexpearce** [comment]
KK, if people think this looks good then merge it.

**Comment by betatim** [comment]
Can we answer the question of who owns that ANA note first before we send them 40 people editing it?

**Comment by alexpearce** [comment]
As I said, I'm happy to host it. I can copy the template somewhere and we can use that.

**Comment by alexpearce** [comment]
``` bash
$ svn co svn+ssh://svn.cern.ch/reps/lhcbdocs/Users/apearce/LHCbStarterkit
```

**Pull request merged**
