### PR TITLE
Add an introduction to the homepage

### PR DESCRIPTION
**Pull request by alexpearce**
There wasn't one, so this is something. Couldn't think of much more to say…

Got rid of the callout because it's just repeating the prerequisites lesson. Would it be worth adding a sentence saying “make sure you've followed this lesson”, or is that obvious enough given that it's the first lesson?

### CODE REVIEW

**Comment by apuignav** [comment]
I'm afraid it wants 1 and exactly 1 callout with prereq...

**Comment by alexpearce** [comment]
Looks like `make check` [requires there to be at least one `prereq` box on the homepage](https://github.com/lhcb/first-analysis-steps/blob/master/tools/check.py#L459)…

Shall I just put something like “follow the prerequisite lesson”, or would people prefer some more detail? (Like “ssh to lxlus” etc.)

**Comment by betatim** [comment]
I think the idea of the prereq box is to mention also other technical things. We could add a link to the SWC lessons on bash and python. We kind of assume you know your way around the shell and can read python

**Comment by alexpearce** [comment]
Good idea. I'll add a link to our SWC page.

**Comment by alexpearce** [comment]
Done.

**Comment by apuignav** [comment]
Looks good to me.

On Mon, Jun 1, 2015 at 11:09 AM, Alex Pearce notifications@github.com
wrote:

> Done.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lhcb/first-analysis-steps/pull/78#issuecomment-107376642
> .

## 

Dr. Albert Puig Navarro
Laboratoire de Physique des Hautes Energies
Ecole Polytechnique Fédérale de Lausanne (EPFL)
BSP 614.4 (Cubotron UNIL) CH-1015 Lausanne
EPFL Phone: 021 6939808
CERN Phone: 72518

**Comment by betatim** [comment]
Language lawyering: should we call the whole `first-analysis-steps` thing a lesson and each of the pages a topic? Or each of the pages are a lesson each and then we call the whole thing ...(a workshop?)?

**Comment by betatim** [comment]
Otherwise I am happy. Thanks for tidying.

**Comment by alexpearce** [comment]
I would ultimately leave that to an executive decision :wink: For me, each individual step is a lesson, but maybe we should use the SWC lingo.

**Comment by betatim** [comment]
Do we have any text that needs fixing if we decide one way or the other? If not my executive decision tool(tm) says: Heads

**Comment by betatim** [comment]
Merging this for now, we can adjust the language and make it more consistent later.

**Pull request merged**
