### PR TITLE
Turn off Travis email notification

### PR DESCRIPTION
**Pull request by betatim**
I get enough emails, so propose to turn off email notification for travis.

### CODE REVIEW

**Comment by betatim** [comment]
I branched from the wrong branch. Does someone know how to fix that? This PR shouldn't contain `d779019`

**Comment by ibab** [comment]
Only with `push -f` :D

**Comment by ibab** [comment]
Do `git rebase -i HEAD~3` and simply delete the line with the bad commit.

**Comment by ibab** [comment]
Looks good.

**Pull request merged**
