### PR TITLE
Added google analytics snippet

### PR DESCRIPTION
**Pull request by betatim**
Unsure how to test this before it is deployed. Any thoughts?

### CODE REVIEW

**Comment by ibab** [comment]
I think you can just build and view it locally.
That should show up in analytics.

**Comment by ibab** [comment]
Might be more appropriate to put the snippet at the end of `_includes/javascript.html`.

**Comment by betatim** [comment]
Big G told me to include the snippet "just before `</head>`" and the `_includes/javascript.html` get put at the bottom of the page. No experience with this so I just followed the google instructions.

**Comment by ibab** [comment]
Okay, I'd say this is good to merge.

**Comment by betatim** [comment]
This implements the tracking from #69

**Pull request merged**
