### PR TITLE
Minimal DV on the grid (continued)

### PR DESCRIPTION
**Pull request by betatim**
This is a continuation of #39

### CODE REVIEW

**Comment by betatim** [comment]
Basically ready for review and then merging.

Should we add more about `ganga` here? New topic? Just linking?

**Comment by betatim** [comment]
Fixes #9

**Comment by ibab** [comment]
I usually run my job scripts from within `ganga` with `%ganga`.
Is that something people do?
I find this more convenient than closing/starting `ganga`, which takes quite a bit of time.

**Comment by betatim** [comment]
Good point. I reworded it so that we just talk about the "inside ganga" option.

**Comment by betatim** [comment]
Fixes #9

**Pull request merged**
