### PR TITLE
Kerberos in screen

### LINKED ISSUE #36: Kerberos tokens in screen session
Documentation is incomplete.

### PR DESCRIPTION
**Pull request by betatim**
Added description of how to keep your kerberos tokens alive. This is based on an empirical study to find this method. There is also some `kerbpg.sh` script or some such, though I never understood what it does/why it should work.

Fixes #36 reported by @kdungs so he should have a look if this satisfies him

### CODE REVIEW

**Comment by betatim** [comment]
Actually don't like that I don't know if this recipe actually works or just appears to work.

**Comment by kdungs** [comment]
What I usually do is

``` bash
pagsh.krb -c 'kinit && tmux new-session
```

so for you it would be

``` bash
pagsh.krb -c 'kinit && screen'
```

also you will have to renew your token every once in a while (24h I think).

**Comment by betatim** [comment]
This is the strategy I use all the time, and it appears to work.

Do you understand what `pagsh.krb` actually does?

Renew every 24h is unfortunately a thing.

**Comment by apuignav** [comment]
I have a small snippet to find a `screen` when you've lost it in lxplus.

``` bash
for i in $(seq -f "%04g" 1 500); do
     ssh -o StrictHostKeyChecking=no -o LogLevel=quiet lxplus$i.cern.ch  -o ConnectTimeout=10 "hostname && ps faxu | grep `whoami` | grep SCREEN | grep -v grep" | grep -v "No route" | grep -v "Permanently" | grep -B1 SCREEN
done
```

Maybe it's interesting.

**Comment by kdungs** [comment]
Do you use certificate based login for lxplus? Maybe I am overlooking something but right now I don't understand how this would not ask me for my password 500 times.

**Comment by apuignav** [comment]
Argh, actually it doesn't, but I don't remember why. Just run it from lxplus :-)

**Comment by kdungs** [comment]
Ah right that makes sense. Once you have a valid kerberos token that takes care of it.

**Comment by betatim** [comment]
I added a slightly modified version of @apuignav snippet. I find it a little more "obvious" as to what it does. Added the preferred auth options to make sure it uses kerberos tokens, no matter what your `.ssh/config` says.

**Comment by apuignav** [comment]
Nice improvement!

**Pull request merged**
