### PR TITLE
Using the 000001_1 file everywhere, instead of sometimes using 000002_1

### PR DESCRIPTION
**Pull request by henryiii**
This uses just the one file (that ends in `1_1`) everywhere that a single file is used. This is the file suggested at the beginning to download if the system is slow. (If all the files are downloaded at the beginning, it does not make a large difference, other than being more consistent).

### CODE REVIEW

**Comment by henryiii** [comment]
PS: Closes #175.

**Comment by henryiii** [comment]
Note: this does affect some of the plots, so I could use `2_1` everywhere instead. The first plot on the DecayTreeFitter page has one outlier in `1_1`.

c1

**Comment by henryiii** [comment]
The 002_1 file is not available with 

``` bash
xrdcp root://eoslhcb.cern.ch//eos/lhcb/user/a/apearce/Starterkit/Nov2015/00035742_00000002_1.allstreams.dst .
```

**Comment by alexpearce** [comment]
I hope you didn't spend too long being confused on this 😄  Thanks for fixing it.

> The 002_1 file is not available with
> 
> ```
> xrdcp root://eoslhcb.cern.ch//eos/lhcb/user/a/apearce/Starterkit/Nov2015/00035742_00000002_1.allstreams.dst
> ```

Will that be a problem after this PR?

**Comment by henryiii** [comment]
Can you put the 0000002_1 file in your eos directory? Then I can replace the 00001_1's with 00002_1, and the plots will match the ones in the starterkit.

**Comment by alexpearce** [comment]
Sure thing, it's there now.

```
> eos ls /eos/lhcb/user/a/apearce/Starterkit/Nov2015/
00035742_00000001_1.allstreams.dst
00035742_00000002_1.allstreams.dst
```

**Comment by henryiii** [comment]
Okay, the PR should be more consistent now with previous graphs. Thanks! 🙇

**Comment by betatim** [comment]
Can this be merged?

**Comment by alexpearce** [comment]
:+1:

Thanks a lot @henryiii 👏

**Comment by betatim** [comment]
🍰 🍰 🍰

**Pull request merged**
