### PR TITLE
[WIP] Introductory slides

### PR DESCRIPTION
**Pull request by apuignav**
Only the title is there, but better start the PR early.

Will be turned into a lesson afterwards.

### CODE REVIEW

**Comment by ibab** [comment]
Pinging @apuignav: What's the status of the slides? Will you be able to finish them before the start of the workshop?

**Comment by apuignav** [comment]
We don't need them anymore, right? The SP is giving the talk...

**Comment by ibab** [comment]
Ah, of course. But it would still be good to figure out what to tell the participants beforehand.
We can talk about it on Monday morning :)

**Comment by apuignav** [comment]
I was thinking of a small speech, explaining the basics. My plan was to
improvise :-)

**Comment by ibab** [comment]
Sounds good :)

**Pull request closed without merging**
