### PR TITLE
Update 22-ecgd.md

### PR DESCRIPTION
**Pull request by bsciasci**
A few words about the ECGD and its function

### CODE REVIEW

**Comment by apuignav** [comment]
Looks good to me!

Didn't you want to also link to some slides that will be shown by Jonas?

**Comment by bsciasci** [comment]
Fine with me... even if before Jonas should prepare the slides ;-)

**Comment by betatim** [comment]
L20: officiers -> officers

LGTM

**Comment by alexpearce** [comment]
I'm not sure I'm entirely comfortable with the parenthetical “including white middle class heterosexual male ones”. It came out of nowhere, in that I didn't see the relation to the previous sentence.

I understand that it's almost a meme when discussing equality issues, as the ”white middle class heterosexual male” is usually considered the most ‘privileged’, but unless the reader has experience with that debate then they probably won't understand the reference (and it feels like it's referencing something).

If the purpose was just to state explicitly that the ‘early-career’ part also involves people who don't feel that they experience discrimination, I would just say so more plainly, perhaps even starting a new paragraph as the two roles are quite different.

> The aim of the ECGD is to help LHCb achieve a working environment in which all LHCb members can thrive. This includes especially those experiencing discrimination on grounds of gender, sexual orientation, ethnicity, disability, creed, cultural background or other factors.
> 
> The ECGD also helps early-career physicists who wish to, eventually, escape the precarious life of repeated short-term contracts and reach a permanent position. You can find more information and a lot of documentation in the [ECGD web page](http://lhcb.web.cern.ch/lhcb/ECGD_Office/ECGD-intro.html).

**Comment by bsciasci** [comment]
Hi Alex, I agree with you. I wanted remove that part and then I forgot. As you notice the sentence comes out of the blue here and is particularly inappropriate in the SterterKit context.
I'm fine with your rewording.

**Comment by betatim** [comment]
To avoid confusion/misunderstanding. @bsciasci you will implement those changes to the white males and fix the spelling mistake in officers right?

(technically you can do this by making another commit and pushing it to your fork)

**Comment by bsciasci** [comment]
Done (in principle... GitHub is still a bit mysterious for me ;-) )

**Comment by alexpearce** [comment]
Awesome, thanks a lot Barbara!

**Comment by betatim** [comment]
Today must be a special day, another first contributor! We send the usual gifts of :cake: and :ice_cream:

**Comment by bsciasci** [comment]
:sunglasses: :beer:

**Pull request merged**
